### ISSUE TITLE
Add Delay Stop And Complete

### ISSUE THREAD

**Issue by tiantianaixuexi** [zompi2/UE4EnhancedCodeFlow#5]
You can add a function that stop the Delay and executes the Delay CallBack directly.

**Comment by tiantianaixuexi** [comment]
[EnhancedCodeFlow.zip](https://github.com/zompi2/UE4EnhancedCodeFlow/files/6363422/EnhancedCodeFlow.zip)

**Comment by zompi2** [comment]
Thank you for a suggestion, will look at it soon.

**Comment by zompi2** [comment]
Added functionality to version 1.4.0.
Now every `StopAction` function must receive a parameter `bComplete` if it want to launch a Callback or not. It should work for every implemented Action (except `WhileTrueExecute`).
