### ISSUE TITLE
Separate the plugin from the example project

### ISSUE THREAD

**Issue by fabriciomsantos** [zompi2/UE4EnhancedCodeFlow#9]
Make a repository just for the plugin and use this repository for the example project, then add the plugin repository  as a submodule on this repository.
This will make it easier to add the plugin to other projects as a submodule and keep the plugin updated.

**Comment by zompi2** [comment]
Interesting concept. I will do it in free time :)

**Comment by fabriciomsantos** [comment]
Example of a project doing this:
https://github.com/sinbad/SPUDExamples
https://github.com/sinbad/SPUD

**Comment by zompi2** [comment]
The example project has been created here: https://github.com/zompi2/UE4EnhancedCodeFlowExample
